name: 'streamforge'
version: '1.0.0'
config-version: 2

profile: 'streamforge'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  streamforge:
    staging:
      +materialized: view
    marts:
      +materialized: table

seeds:
  streamforge:
    +quote_columns: true

